class CreateCommandGroups < ActiveRecord::Migration
  def self.up
    create_table :command_groups do |t|
      t.string, :Description
      t.String, :Hint
      t.boolean, :CanTurnOff
      t.boolean, :AlwaysShow
      t.boolean, :CanBeHidden
      t.integer, :AltID
      t.datetime, :AutoGeneratedDate
      t.boolean, :Disabled
      t.integer, :TemplateParm1
      t.integer :TemplateParm2

      t.timestamps
    end
  end

  def self.down
    drop_table :command_groups
  end
end
